import type { ProductCategoryConfig } from "@/lib/calculator/calculator.types";

export const CALCULATOR_PRODUCTS: ProductCategoryConfig[] = [
  {
    id: "pemzablok",
    nameKey: "pemzablok",
    unitLabelKey: "blocks",
    image: "/images/applications/placeholders/residential.svg",
    calculationType: "wall_blocks",
    variants: [
      {
        id: "pumice-6x20x40",
        nameKey: "block6",
        image: "/images/products/pumice-blocks/pumice-6x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 6,
        itemsPerPallet: 150,
        pricePerUnit: 180,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-10x20x40",
        nameKey: "block10",
        image: "/images/products/pumice-blocks/pumice-10x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 10,
        itemsPerPallet: 100,
        pricePerUnit: 240,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-15x20x40",
        nameKey: "block15",
        image: "/images/products/pumice-blocks/pumice-15x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 15,
        itemsPerPallet: 75,
        pricePerUnit: 300,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-20x20x40",
        nameKey: "block20",
        image: "/images/products/pumice-blocks/pumice-20x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 20,
        itemsPerPallet: 60,
        pricePerUnit: 360,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-20x20x40-groove",
        nameKey: "block20Groove",
        image: "/images/products/pumice-blocks/pumice-20x20x40-groove.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 20,
        itemsPerPallet: 60,
        pricePerUnit: 390,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "concrete-block",
    nameKey: "concreteBlock",
    unitLabelKey: "blocks",
    image: "/images/applications/placeholders/industrial.svg",
    calculationType: "wall_blocks",
    variants: [
      {
        id: "concrete-block-15",
        nameKey: "concreteBlock15",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 15,
        itemsPerPallet: 70,
        pricePerUnit: 290,
        pricingUnit: "per_item",
      },
      {
        id: "concrete-block-20",
        nameKey: "concreteBlock20",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 20,
        itemsPerPallet: 60,
        pricePerUnit: 340,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "concrete",
    nameKey: "concrete",
    unitLabelKey: "m3",
    image: "/images/applications/placeholders/industrial.svg",
    calculationType: "concrete_volume",
    variants: [
      {
        id: "concrete-m250",
        nameKey: "concreteM250",
        pricePerUnit: 32000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m300",
        nameKey: "concreteM300",
        pricePerUnit: 35000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m350",
        nameKey: "concreteM350",
        pricePerUnit: 38000,
        pricingUnit: "per_cubic_meter",
      },
    ],
  },
  {
    id: "paving-stones",
    nameKey: "pavingStones",
    unitLabelKey: "m2",
    image: "/images/applications/placeholders/landscape.svg",
    calculationType: "paving_area",
    variants: [
      {
        id: "paving-rectangle-sand-v1",
        nameKey: "pavingRectangleSandV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-square-sand-v1",
        nameKey: "pavingSquareSandV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-rectangle-brown-v1",
        nameKey: "pavingRectangleBrownV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-rectangle-gray-v1",
        nameKey: "pavingRectangleGrayV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-square-brown-v1",
        nameKey: "pavingSquareBrownV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-rectangle-red-v1",
        nameKey: "pavingRectangleRedV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-rectangle-gray-v2",
        nameKey: "pavingRectangleGrayV2",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-rectangle-dark-gray-v1",
        nameKey: "pavingRectangleDarkGrayV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-rectangle-light-gray-v1",
        nameKey: "pavingRectangleLightGrayV1",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_sq_meter",
      },
    ],
  },

  {
    id: "curbstones",
    nameKey: "curbstones",
    unitLabelKey: "lm",
    image: "/images/applications/placeholders/road.svg",
    calculationType: "curbstones",
    variants: [
      {
        id: "curbstone-road-1m",
        nameKey: "curbstoneRoad100",
        lengthMeters: 1.0,
        heightMeters: 0.3,
        thicknessCm: 15,
        itemsPerLinearMeter: 1,
        itemsPerPallet: 20,
        pricePerUnit: 2800,
        pricingUnit: "per_item",
      },
      {
        id: "curbstone-sidewalk-05m",
        nameKey: "curbstoneSidewalk50",
        lengthMeters: 0.5,
        heightMeters: 0.2,
        thicknessCm: 8,
        itemsPerLinearMeter: 2,
        itemsPerPallet: 40,
        pricePerUnit: 1400,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "manholes",
    nameKey: "manholes",
    unitLabelKey: "pcs",
    image: "/images/applications/placeholders/public-building.svg",
    calculationType: "quantity_product",
    variants: [
      {
        id: "manhole-small-v1",
        nameKey: "manholeSmallV1",
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_item",
      },
      {
        id: "manhole-large-v1",
        nameKey: "manholeLargeV1",
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_item",
      },
      {
        id: "manhole-single-cover-v1-small",
        nameKey: "manholeSingleCoverV1Small",
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_item",
      },
      {
        id: "manhole-double-cover-v1-small",
        nameKey: "manholeDoubleCoverV1Small",
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-square-opening-v1-small",
        nameKey: "manholeCoverSquareOpeningV1Small",
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-slot-v1-small",
        nameKey: "manholeCoverSlotV1Small",
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-round-hole-v1-small",
        nameKey: "manholeCoverRoundHoleV1Small",
        pricePerUnit: 0,
        priceStatus: "to_be_confirmed",
        pricingUnit: "per_item",
      },
    ],
  },
];
