import type { ProductCategoryConfig } from "@/lib/calculator/calculator.types";

export const CALCULATOR_PRODUCTS: ProductCategoryConfig[] = [
  {
    id: "pemzablok",
    nameKey: "pemzablok",
    unitLabelKey: "blocks",
    image: "/images/applications/placeholders/residential.svg",
    calculationType: "wall_blocks",
    variants: [
      {
        id: "pemzablok-20",
        nameKey: "block20",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 20,
        itemsPerPallet: 60,
        pricePerUnit: 320,
        pricingUnit: "per_item",
      },
      {
        id: "pemzablok-25",
        nameKey: "block25",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 25,
        itemsPerPallet: 50,
        pricePerUnit: 380,
        pricingUnit: "per_item",
      },
      {
        id: "pemzablok-30",
        nameKey: "block30",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 30,
        itemsPerPallet: 40,
        pricePerUnit: 440,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "concrete-block",
    nameKey: "concreteBlock",
    unitLabelKey: "blocks",
    image: "/images/applications/placeholders/industrial.svg",
    calculationType: "wall_blocks",
    variants: [
      {
        id: "concrete-block-15",
        nameKey: "concreteBlock15",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 15,
        itemsPerPallet: 70,
        pricePerUnit: 290,
        pricingUnit: "per_item",
      },
      {
        id: "concrete-block-20",
        nameKey: "concreteBlock20",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 20,
        itemsPerPallet: 60,
        pricePerUnit: 340,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "concrete",
    nameKey: "concrete",
    unitLabelKey: "m3",
    image: "/images/applications/placeholders/industrial.svg",
    calculationType: "concrete_volume",
    variants: [
      {
        id: "concrete-m250",
        nameKey: "concreteM250",
        pricePerUnit: 32000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m300",
        nameKey: "concreteM300",
        pricePerUnit: 35000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m350",
        nameKey: "concreteM350",
        pricePerUnit: 38000,
        pricingUnit: "per_cubic_meter",
      },
    ],
  },
  {
    id: "paving-stones",
    nameKey: "pavingStones",
    unitLabelKey: "m2",
    image: "/images/applications/placeholders/landscape.svg",
    calculationType: "paving_area",
    variants: [
      {
        id: "paving-classic-6cm",
        nameKey: "pavingClassic6",
        itemsPerSqMeter: 50,
        thicknessCm: 6,
        itemsPerPallet: 500,
        pricePerUnit: 4200,
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-classic-8cm",
        nameKey: "pavingClassic8",
        itemsPerSqMeter: 50,
        thicknessCm: 8,
        itemsPerPallet: 400,
        pricePerUnit: 4800,
        pricingUnit: "per_sq_meter",
      },
    ],
  },

  {
    id: "curbstones",
    nameKey: "curbstones",
    unitLabelKey: "lm",
    image: "/images/applications/placeholders/road.svg",
    calculationType: "curbstones",
    variants: [
      {
        id: "curbstone-road-1m",
        nameKey: "curbstoneRoad100",
        lengthMeters: 1.0,
        heightMeters: 0.3,
        thicknessCm: 15,
        itemsPerLinearMeter: 1,
        itemsPerPallet: 20,
        pricePerUnit: 2800,
        pricingUnit: "per_item",
      },
      {
        id: "curbstone-sidewalk-05m",
        nameKey: "curbstoneSidewalk50",
        lengthMeters: 0.5,
        heightMeters: 0.2,
        thicknessCm: 8,
        itemsPerLinearMeter: 2,
        itemsPerPallet: 40,
        pricePerUnit: 1400,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "manholes",
    nameKey: "manholes",
    unitLabelKey: "pcs",
    image: "/images/applications/placeholders/public-building.svg",
    calculationType: "quantity_product",
    variants: [
      {
        id: "manhole-ring-100",
        nameKey: "manholeRing100",
        pricePerUnit: 28000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-100",
        nameKey: "manholeCover100",
        pricePerUnit: 22000,
        pricingUnit: "per_item",
      },
    ],
  },
];
