import type { ProductCategoryConfig } from "@/lib/calculator/calculator.types";

export const CALCULATOR_PRODUCTS: ProductCategoryConfig[] = [
  {
    id: "pemzablok",
    nameKey: "pemzablok",
    unitLabelKey: "blocks",
    image: "/images/products/pumice-blocks/pemzablok.png",
    calculationType: "wall_blocks",
    variants: [
      {
        id: "pumice-6x20x40",
        nameKey: "block6",
        image: "/images/products/pumice-blocks/pumice-6x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 6,
        itemsPerPallet: 150,
        pricePerUnit: 150,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-10x20x40",
        nameKey: "block10",
        image: "/images/products/pumice-blocks/pumice-10x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 10,
        itemsPerPallet: 100,
        pricePerUnit: 155,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-15x20x40",
        nameKey: "block15",
        image: "/images/products/pumice-blocks/pumice-15x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 15,
        itemsPerPallet: 75,
        pricePerUnit: 200,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-20x20x40",
        nameKey: "block20",
        image: "/images/products/pumice-blocks/pumice-20x20x40.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 20,
        itemsPerPallet: 60,
        pricePerUnit: 225,
        pricingUnit: "per_item",
      },
      {
        id: "pumice-20x20x40-groove",
        nameKey: "block20Groove",
        image: "/images/products/pumice-blocks/pumice-20x20x40-groove.webp",
        lengthMeters: 0.4,
        heightMeters: 0.2,
        thicknessCm: 20,
        itemsPerPallet: 60,
        pricePerUnit: 215,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "concrete-block",
    nameKey: "concreteBlock",
    unitLabelKey: "pcs",
    image: "/images/products/concrete-blocks/concrete-block.png",
    calculationType: "floor_slabs",
    variants: [
      {
        id: "slab-120",
        nameKey: "slab120",
        image: "/images/products/concrete-blocks/concrete-block.png",
        widthMeters: 1.20,
        pricePerUnit: 8500,
        pricingUnit: "per_sq_meter",
      },
      {
        id: "slab-060",
        nameKey: "slab060",
        image: "/images/products/concrete-blocks/concrete-block.png",
        widthMeters: 0.60,
        pricePerUnit: 8500,
        pricingUnit: "per_sq_meter",
      },
    ],
  },
  {
    id: "concrete",
    nameKey: "concrete",
    unitLabelKey: "m3",
    image: "/images/products/ready-mix-concrete/concrete.png",
    calculationType: "concrete_volume",
    variants: [
      {
        id: "concrete-m100",
        nameKey: "concreteM100",
        image: "/images/products/ready-mix-concrete/concrete.png",
        pricePerUnit: 25000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m150",
        nameKey: "concreteM150",
        image: "/images/products/ready-mix-concrete/concrete.png",
        pricePerUnit: 27000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m200",
        nameKey: "concreteM200",
        image: "/images/products/ready-mix-concrete/concrete.png",
        pricePerUnit: 30000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m250",
        nameKey: "concreteM250",
        image: "/images/products/ready-mix-concrete/concrete.png",
        pricePerUnit: 31000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m300",
        nameKey: "concreteM300",
        image: "/images/products/ready-mix-concrete/concrete.png",
        pricePerUnit: 32000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m350",
        nameKey: "concreteM350",
        image: "/images/products/ready-mix-concrete/concrete.png",
        pricePerUnit: 34000,
        pricingUnit: "per_cubic_meter",
      },
      {
        id: "concrete-m400",
        nameKey: "concreteM400",
        image: "/images/products/ready-mix-concrete/concrete.png",
        pricePerUnit: 38000,
        pricingUnit: "per_cubic_meter",
      },
    ],
  },
  {
    id: "paving-stones",
    nameKey: "pavingStones",
    unitLabelKey: "m2",
    image: "/images/products/paving-stones/paving-stone-type-1.png",
    calculationType: "paving_area",
    variants: [
      {
        id: "paving-type-1",
        nameKey: "pavingType1",
        image: "/images/products/paving-stones/paving-stone-type-1.png",
        itemsPerSqMeter: 50,
        thicknessCm: 5.5,
        itemsPerPallet: 500,
        pricePerUnit: 4000,
        pricingUnit: "per_sq_meter",
      },
      {
        id: "paving-type-2",
        nameKey: "pavingType2",
        image: "/images/products/paving-stones/paving-stone-type-2.png",
        itemsPerSqMeter: 50,
        thicknessCm: 5.5,
        itemsPerPallet: 500,
        pricePerUnit: 4000,
        pricingUnit: "per_sq_meter",
      },
    ],
  },
  {
    id: "curbstones",
    nameKey: "curbstones",
    unitLabelKey: "lm",
    image: "/images/products/curbstones/curbstones.png",
    calculationType: "curbstones",
    variants: [
      {
        id: "curbstone-road",
        nameKey: "curbstoneRoad",
        image: "/images/products/curbstones/curbstones.png",
        lengthMeters: 0.8,
        heightMeters: 0.3,
        thicknessCm: 15,
        itemsPerLinearMeter: 1.25,
        itemsPerPallet: 18,
        pricePerUnit: 4000,
        pricingUnit: "per_item",
      },
      {
        id: "curbstone-garden",
        nameKey: "curbstoneGarden",
        image: "/images/products/curbstones/curbstones.png",
        lengthMeters: 0.8,
        heightMeters: 0.2,
        thicknessCm: 8,
        itemsPerLinearMeter: 1.25,
        itemsPerPallet: 36,
        pricePerUnit: 4000,
        pricingUnit: "per_item",
      },
    ],
  },
  {
    id: "manholes",
    nameKey: "manholes",
    unitLabelKey: "pcs",
    image: "/images/products/manholes/manhole-small-v1.webp",
    calculationType: "quantity_product",
    variants: [
      {
        id: "manhole-small-v1",
        nameKey: "manholeSmallV1",
        image: "/images/products/manholes/manhole-small-v1.webp",
        pricePerUnit: 18000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-large-v1",
        nameKey: "manholeLargeV1",
        image: "/images/products/manholes/manhole-small-v1.webp",
        pricePerUnit: 32000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-single-cover-v1-small",
        nameKey: "manholeSingleCoverV1Small",
        image: "/images/products/manholes/manhole-single-cover-v1-small.webp",
        pricePerUnit: 68000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-double-cover-v1-small",
        nameKey: "manholeDoubleCoverV1Small",
        image: "/images/products/manholes/manhole-double-cover-v1-small.webp",
        pricePerUnit: 75000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-square-opening-v1-small",
        nameKey: "manholeCoverSquareOpeningV1Small",
        image: "/images/products/manholes/manhole-cover-square-opening-v1-small.webp",
        pricePerUnit: 18000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-slot-v1-small",
        nameKey: "manholeCoverSlotV1Small",
        image: "/images/products/manholes/manhole-cover-slot-v1-small.webp",
        pricePerUnit: 18000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-round-hole-v1-small",
        nameKey: "manholeCoverRoundHoleV1Small",
        image: "/images/products/manholes/manhole-cover-round-hole-v1-small.webp",
        pricePerUnit: 18000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-square-opening-v1-large",
        nameKey: "manholeCoverSquareOpeningV1Large",
        image: "/images/products/manholes/manhole-cover-square-opening-v1-small.webp",
        pricePerUnit: 32000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-slot-v1-large",
        nameKey: "manholeCoverSlotV1Large",
        image: "/images/products/manholes/manhole-cover-slot-v1-small.webp",
        pricePerUnit: 32000,
        pricingUnit: "per_item",
      },
      {
        id: "manhole-cover-round-hole-v1-large",
        nameKey: "manholeCoverRoundHoleV1Large",
        image: "/images/products/manholes/manhole-cover-round-hole-v1-small.webp",
        pricePerUnit: 32000,
        pricingUnit: "per_item",
      },
    ],
  },
];
