/**
 * Future Naming & File Placement Rule:
 * Every product image must be stored inside its dedicated product category folder:
 * - public/images/products/pumice-blocks/
 * - public/images/products/concrete-blocks/
 * - public/images/products/ready-mix-concrete/
 * - public/images/products/paving-stones/
 * - public/images/products/curbstones/
 * - public/images/products/manholes/
 * - public/images/products/tiles/
 * 
 * Future real images must never be added directly to public/images/products/.
 */

export interface VariantPrice {
  amount: number;
  currency: string;
  unitKey: string; // e.g., "pcs" or "m3"
}

export interface VariantSpecification {
  labelKey: string;
  valueRaw: string;
}

export interface VariantCalculatorConfiguration {
  calculatorProductId: string;
  calculatorVariantId: string;
  lengthMeters: number;
  heightMeters: number;
  thicknessCm: number;
  itemsPerPallet: number;
  pricePerUnit: number;
  weightKg: number;
}

export interface ProductVariant {
  id: string;
  slug: string;
  sizeLabel: string; // e.g. "6 × 20 × 40"
  sizeLabelKey?: string;
  subtitleKey: string; // e.g. "variants.subtitle6"
  dimensions: string; // "400 × 60 × 200 мм"
  price: VariantPrice;
  priceStatus?: "to_be_confirmed" | "confirmed";
  weightKg: number;
  itemsPerPallet: number;
  inStock: boolean;
  badgeKey?: string;
  image: string; // "/images/products/pumice-6x20x40.webp"
  thumbnail?: string; // "/images/products/pumice-6x20x40.webp"
  altKey?: string; // "variants.alt6"
  fallbackImage: string; // "/images/products/pemzablok.png"
  descriptionKey: string;
  specs: VariantSpecification[];
  calculatorConfig: VariantCalculatorConfiguration;
  type?: "manhole" | "cover";
  size?: "1000" | "1500";
  titleKey?: string;
}

export interface ProductSpec {
  labelKey: string;
  valueKey?: string;
  valueRaw?: string;
}

export interface ProductFeature {
  icon: "eco" | "shield" | "flame" | "ruler" | "coins" | "layers" | "truck" | "check";
  titleKey: string;
  descKey: string;
}

export interface ProductAccessoryOption {
  id: string;
  labelKey: string;
  priceAmount: number;
}

export interface ProductAccessoryGroup {
  id: string;
  nameKey: string;
  options: ProductAccessoryOption[];
}

export interface ProductDetailData {
  id: string;

  slug: string;
  translationKey: string;
  image: string;
  galleryImages: string[];
  badgeKey: string;
  calculatorProductId?: string;
  defaultVariantId: string;
  variants: ProductVariant[];
  specs: ProductSpec[];
  features: ProductFeature[];
  applicationKeys: string[];
  accessoryGroups?: ProductAccessoryGroup[];
}

export const PRODUCT_DETAILS: Record<string, ProductDetailData> = {
  pemzablok: {
    id: "pemzablok",
    slug: "pemzablok",
    translationKey: "pemzablok",
    image: "/images/products/pumice-blocks/pemzablok.png",
    galleryImages: ["/images/products/pumice-blocks/pemzablok.png"],
    badgeKey: "inStockFactory",
    calculatorProductId: "pemzablok",
    defaultVariantId: "pumice-20x20x40",
    variants: [
      {
        id: "pumice-6x20x40",
        slug: "pumice-6x20x40",
        sizeLabel: "6 × 20 × 40",
        subtitleKey: "variants.partitionThin",
        dimensions: "400 × 60 × 200 мм",
        price: { amount: 180, currency: "AMD", unitKey: "perPcs" },
        weightKg: 5.5,
        itemsPerPallet: 150,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/pumice-blocks/pumice-6x20x40.webp",
        thumbnail: "/images/products/pumice-blocks/pumice-6x20x40.webp",
        altKey: "calculator.blocks.block6",
        fallbackImage: "/images/products/pumice-blocks/pemzablok.png",
        descriptionKey: "variants.desc6",
        specs: [
          { labelKey: "dimensions", valueRaw: "400 × 60 × 200 мм" },
          { labelKey: "density", valueRaw: "800 - 850 кг/м³" },
          { labelKey: "weightPerUnit", valueRaw: "5.5 кг" },
          { labelKey: "compressiveStrength", valueRaw: "M35" },
          { labelKey: "thermalConductivity", valueRaw: "0.18 Вт/(м·°C)" },
          { labelKey: "soundInsulation", valueRaw: "44 дБ" },
          { labelKey: "fireResistance", valueRaw: "REI 120" },
          { labelKey: "palletCapacity", valueRaw: "150 шт" },
        ],
        calculatorConfig: {
          calculatorProductId: "pemzablok",
          calculatorVariantId: "pumice-6x20x40",
          lengthMeters: 0.4,
          heightMeters: 0.2,
          thicknessCm: 6,
          itemsPerPallet: 150,
          pricePerUnit: 180,
          weightKg: 5.5,
        },
      },
      {
        id: "pumice-10x20x40",
        slug: "pumice-10x20x40",
        sizeLabel: "10 × 20 × 40",
        subtitleKey: "variants.partitionStandard",
        dimensions: "400 × 100 × 200 мм",
        price: { amount: 240, currency: "AMD", unitKey: "perPcs" },
        weightKg: 8.0,
        itemsPerPallet: 100,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/pumice-blocks/pumice-10x20x40.webp",
        thumbnail: "/images/products/pumice-blocks/pumice-10x20x40.webp",
        altKey: "calculator.blocks.block10",
        fallbackImage: "/images/products/pumice-blocks/pemzablok.png",
        descriptionKey: "variants.desc10",
        specs: [
          { labelKey: "dimensions", valueRaw: "400 × 100 × 200 мм" },
          { labelKey: "density", valueRaw: "850 - 900 кг/м³" },
          { labelKey: "weightPerUnit", valueRaw: "8.0 кг" },
          { labelKey: "compressiveStrength", valueRaw: "M35" },
          { labelKey: "thermalConductivity", valueRaw: "0.19 Вт/(м·°C)" },
          { labelKey: "soundInsulation", valueRaw: "48 дБ" },
          { labelKey: "fireResistance", valueRaw: "REI 180" },
          { labelKey: "palletCapacity", valueRaw: "100 шт" },
        ],
        calculatorConfig: {
          calculatorProductId: "pemzablok",
          calculatorVariantId: "pumice-10x20x40",
          lengthMeters: 0.4,
          heightMeters: 0.2,
          thicknessCm: 10,
          itemsPerPallet: 100,
          pricePerUnit: 240,
          weightKg: 8.0,
        },
      },
      {
        id: "pumice-15x20x40",
        slug: "pumice-15x20x40",
        sizeLabel: "15 × 20 × 40",
        subtitleKey: "variants.semiBearing",
        dimensions: "400 × 150 × 200 мм",
        price: { amount: 300, currency: "AMD", unitKey: "perPcs" },
        weightKg: 11.5,
        itemsPerPallet: 75,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/pumice-blocks/pumice-15x20x40.webp",
        thumbnail: "/images/products/pumice-blocks/pumice-15x20x40.webp",
        altKey: "calculator.blocks.block15",
        fallbackImage: "/images/products/pumice-blocks/pemzablok.png",
        descriptionKey: "variants.desc15",
        specs: [
          { labelKey: "dimensions", valueRaw: "400 × 150 × 200 мм" },
          { labelKey: "density", valueRaw: "900 - 950 кг/м³" },
          { labelKey: "weightPerUnit", valueRaw: "11.5 кг" },
          { labelKey: "compressiveStrength", valueRaw: "M50" },
          { labelKey: "thermalConductivity", valueRaw: "0.20 Вт/(м·°C)" },
          { labelKey: "soundInsulation", valueRaw: "50 дБ" },
          { labelKey: "fireResistance", valueRaw: "REI 180" },
          { labelKey: "palletCapacity", valueRaw: "75 шт" },
        ],
        calculatorConfig: {
          calculatorProductId: "pemzablok",
          calculatorVariantId: "pumice-15x20x40",
          lengthMeters: 0.4,
          heightMeters: 0.2,
          thicknessCm: 15,
          itemsPerPallet: 75,
          pricePerUnit: 300,
          weightKg: 11.5,
        },
      },
      {
        id: "pumice-20x20x40",
        slug: "pumice-20x20x40",
        sizeLabel: "20 × 20 × 40",
        subtitleKey: "variants.loadBearingStandard",
        dimensions: "400 × 200 × 200 мм",
        price: { amount: 360, currency: "AMD", unitKey: "perPcs" },
        weightKg: 14.0,
        itemsPerPallet: 60,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/pumice-blocks/pumice-20x20x40.webp",
        thumbnail: "/images/products/pumice-blocks/pumice-20x20x40.webp",
        altKey: "calculator.blocks.block20",
        fallbackImage: "/images/products/pumice-blocks/pemzablok.png",
        descriptionKey: "variants.desc20",
        specs: [
          { labelKey: "dimensions", valueRaw: "400 × 200 × 200 мм" },
          { labelKey: "density", valueRaw: "950 - 1000 кг/м³" },
          { labelKey: "weightPerUnit", valueRaw: "14.0 кг" },
          { labelKey: "compressiveStrength", valueRaw: "M50" },
          { labelKey: "thermalConductivity", valueRaw: "0.21 Вт/(м·°C)" },
          { labelKey: "soundInsulation", valueRaw: "52 дБ" },
          { labelKey: "fireResistance", valueRaw: "REI 180" },
          { labelKey: "palletCapacity", valueRaw: "60 шт" },
        ],
        calculatorConfig: {
          calculatorProductId: "pemzablok",
          calculatorVariantId: "pumice-20x20x40",
          lengthMeters: 0.4,
          heightMeters: 0.2,
          thicknessCm: 20,
          itemsPerPallet: 60,
          pricePerUnit: 360,
          weightKg: 14.0,
        },
      },
      {
        id: "pumice-20x20x40-groove",
        slug: "pumice-20x20x40-groove",
        sizeLabel: "20 × 20 × 40 (Groove)",
        subtitleKey: "variants.loadBearingGroove",
        dimensions: "400 × 200 × 200 мм (Ակոսավոր / Паз)",
        price: { amount: 390, currency: "AMD", unitKey: "perPcs" },
        weightKg: 13.8,
        itemsPerPallet: 60,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/pumice-blocks/pumice-20x20x40-groove.webp",
        thumbnail: "/images/products/pumice-blocks/pumice-20x20x40-groove.webp",
        altKey: "calculator.blocks.block20Groove",
        fallbackImage: "/images/products/pumice-blocks/pemzablok.png",
        descriptionKey: "variants.desc20Groove",
        specs: [
          { labelKey: "dimensions", valueRaw: "400 × 200 × 200 мм (Шпунтованный)" },
          { labelKey: "density", valueRaw: "950 - 1000 кг/м³" },
          { labelKey: "weightPerUnit", valueRaw: "13.8 кг" },
          { labelKey: "compressiveStrength", valueRaw: "M50" },
          { labelKey: "thermalConductivity", valueRaw: "0.20 Вт/(м·°C)" },
          { labelKey: "soundInsulation", valueRaw: "53 дБ" },
          { labelKey: "fireResistance", valueRaw: "REI 180" },
          { labelKey: "palletCapacity", valueRaw: "60 шт" },
        ],
        calculatorConfig: {
          calculatorProductId: "pemzablok",
          calculatorVariantId: "pumice-20x20x40-groove",
          lengthMeters: 0.4,
          heightMeters: 0.2,
          thicknessCm: 20,
          itemsPerPallet: 60,
          pricePerUnit: 390,
          weightKg: 13.8,
        },
      },
    ],
    specs: [
      { labelKey: "dimensions", valueRaw: "400 × (60-200) × 200 мм" },
      { labelKey: "density", valueRaw: "800 - 1000 кг/м³" },
      { labelKey: "compressiveStrength", valueRaw: "M35 - M50" },
      { labelKey: "thermalConductivity", valueRaw: "0.18 - 0.22 Вт/(м·°C)" },
      { labelKey: "soundInsulation", valueRaw: "44 - 53 дБ" },
      { labelKey: "frostResistance", valueRaw: "F50+" },
      { labelKey: "fireResistance", valueRaw: "REI 180" },
    ],
    features: [
      {
        icon: "eco",
        titleKey: "features.ecoPumice.title",
        descKey: "features.ecoPumice.desc",
      },
      {
        icon: "shield",
        titleKey: "features.thermalInsulation.title",
        descKey: "features.thermalInsulation.desc",
      },
      {
        icon: "flame",
        titleKey: "features.fireproof.title",
        descKey: "features.fireproof.desc",
      },
      {
        icon: "ruler",
        titleKey: "features.preciseGeometry.title",
        descKey: "features.preciseGeometry.desc",
      },
      {
        icon: "layers",
        titleKey: "features.soundproofing.title",
        descKey: "features.soundproofing.desc",
      },
      {
        icon: "coins",
        titleKey: "features.costEffective.title",
        descKey: "features.costEffective.desc",
      },
    ],
    applicationKeys: [
      "applications.exteriorWalls",
      "applications.interiorPartitions",
      "applications.monolithicFill",
      "applications.soundproofWalls",
      "applications.privateResidential",
      "applications.commercialBuildings",
    ],
  },

  "concrete-block": {
    id: "concrete-block",
    slug: "concrete-block",
    translationKey: "concrete-block",
    image: "/images/products/concrete-blocks/concrete-block.png",
    galleryImages: ["/images/products/concrete-blocks/concrete-block.png"],
    badgeKey: "inStockFactory",
    calculatorProductId: "concrete-block",
    defaultVariantId: "concrete-block-20",
    variants: [
      {
        id: "concrete-block-15",
        slug: "concrete-block-15",
        sizeLabel: "15 × 20 × 40",
        subtitleKey: "variants.concreteBlock15",
        dimensions: "400 × 150 × 200 мм",
        price: { amount: 290, currency: "AMD", unitKey: "perPcs" },
        weightKg: 16.0,
        itemsPerPallet: 70,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/concrete-blocks/concrete-block.png",
        fallbackImage: "/images/products/concrete-blocks/concrete-block.png",
        descriptionKey: "descriptions.concrete-block",
        specs: [
          { labelKey: "dimensions", valueRaw: "400 × 150 × 200 мм" },
          { labelKey: "compressiveStrength", valueRaw: "M75" },
        ],
        calculatorConfig: {
          calculatorProductId: "concrete-block",
          calculatorVariantId: "concrete-block-15",
          lengthMeters: 0.4,
          heightMeters: 0.2,
          thicknessCm: 15,
          itemsPerPallet: 70,
          pricePerUnit: 290,
          weightKg: 16.0,
        },
      },
      {
        id: "concrete-block-20",
        slug: "concrete-block-20",
        sizeLabel: "20 × 20 × 40",
        subtitleKey: "variants.concreteBlock20",
        dimensions: "400 × 200 × 200 мм",
        price: { amount: 340, currency: "AMD", unitKey: "perPcs" },
        weightKg: 20.0,
        itemsPerPallet: 60,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/concrete-blocks/concrete-block.png",
        fallbackImage: "/images/products/concrete-blocks/concrete-block.png",
        descriptionKey: "descriptions.concrete-block",
        specs: [
          { labelKey: "dimensions", valueRaw: "400 × 200 × 200 мм" },
          { labelKey: "compressiveStrength", valueRaw: "M100" },
        ],
        calculatorConfig: {
          calculatorProductId: "concrete-block",
          calculatorVariantId: "concrete-block-20",
          lengthMeters: 0.4,
          heightMeters: 0.2,
          thicknessCm: 20,
          itemsPerPallet: 60,
          pricePerUnit: 340,
          weightKg: 20.0,
        },
      },
    ],
    specs: [
      { labelKey: "dimensions", valueRaw: "400 × 200 × 200 мм" },
      { labelKey: "density", valueRaw: "1200 - 1400 кг/м³" },
      { labelKey: "compressiveStrength", valueRaw: "M75 - M100" },
    ],
    features: [
      {
        icon: "shield",
        titleKey: "features.highStrength.title",
        descKey: "features.highStrength.desc",
      },
    ],
    applicationKeys: [
      "applications.bearingWalls",
      "applications.foundationBlocks",
    ],
  },

  concrete: {
    id: "concrete",
    slug: "concrete",
    translationKey: "concrete",
    image: "/images/products/ready-mix-concrete/concrete.png",
    galleryImages: ["/images/products/ready-mix-concrete/concrete.png"],
    badgeKey: "inStockFactory",
    calculatorProductId: "concrete",
    defaultVariantId: "concrete-m300",
    variants: [
      {
        id: "concrete-m250",
        slug: "concrete-m250",
        sizeLabel: "M250 (B20)",
        subtitleKey: "variants.concreteM250",
        dimensions: "1 м³",
        price: { amount: 32000, currency: "AMD", unitKey: "perM3" },
        weightKg: 2400,
        itemsPerPallet: 1,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/ready-mix-concrete/concrete.png",
        fallbackImage: "/images/products/ready-mix-concrete/concrete.png",
        descriptionKey: "descriptions.concrete",
        specs: [{ labelKey: "grades", valueRaw: "M250 (B20)" }],
        calculatorConfig: {
          calculatorProductId: "concrete",
          calculatorVariantId: "concrete-m250",
          lengthMeters: 1,
          heightMeters: 1,
          thicknessCm: 100,
          itemsPerPallet: 1,
          pricePerUnit: 32000,
          weightKg: 2400,
        },
      },
      {
        id: "concrete-m300",
        slug: "concrete-m300",
        sizeLabel: "M300 (B22.5)",
        subtitleKey: "variants.concreteM300",
        dimensions: "1 м³",
        price: { amount: 35000, currency: "AMD", unitKey: "perM3" },
        weightKg: 2400,
        itemsPerPallet: 1,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/ready-mix-concrete/concrete.png",
        fallbackImage: "/images/products/ready-mix-concrete/concrete.png",
        descriptionKey: "descriptions.concrete",
        specs: [{ labelKey: "grades", valueRaw: "M300 (B22.5)" }],
        calculatorConfig: {
          calculatorProductId: "concrete",
          calculatorVariantId: "concrete-m300",
          lengthMeters: 1,
          heightMeters: 1,
          thicknessCm: 100,
          itemsPerPallet: 1,
          pricePerUnit: 35000,
          weightKg: 2400,
        },
      },
    ],
    specs: [{ labelKey: "grades", valueRaw: "M100 - M400 (B7.5 - B30)" }],
    features: [
      {
        icon: "truck",
        titleKey: "features.expressDelivery.title",
        descKey: "features.expressDelivery.desc",
      },
    ],
    applicationKeys: [
      "applications.monolithicStructures",
      "applications.foundations",
    ],
  },

  "paving-stones": {
    id: "paving-stones",
    slug: "paving-stones",
    translationKey: "paving-stones",
    image: "/images/products/paving-stones/paving-stones.png",
    galleryImages: ["/images/products/paving-stones/paving-stones.png"],
    badgeKey: "inStockFactory",
    calculatorProductId: "paving-stones",
    defaultVariantId: "paving-rectangle-sand-v1",
    variants: [
      {
        id: "paving-rectangle-sand-v1",
        slug: "paving-rectangle-sand-v1",
        titleKey: "variants.pavingRectangleSandV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-rectangle-sand-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-rectangle-sand-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-square-sand-v1",
        slug: "paving-square-sand-v1",
        titleKey: "variants.pavingSquareSandV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-square-sand-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-square-sand-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-rectangle-brown-v1",
        slug: "paving-rectangle-brown-v1",
        titleKey: "variants.pavingRectangleBrownV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-rectangle-brown-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-rectangle-brown-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-rectangle-gray-v1",
        slug: "paving-rectangle-gray-v1",
        titleKey: "variants.pavingRectangleGrayV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-rectangle-gray-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-rectangle-gray-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-square-brown-v1",
        slug: "paving-square-brown-v1",
        titleKey: "variants.pavingSquareBrownV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-square-brown-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-square-brown-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-rectangle-red-v1",
        slug: "paving-rectangle-red-v1",
        titleKey: "variants.pavingRectangleRedV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-rectangle-red-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-rectangle-red-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-rectangle-gray-v2",
        slug: "paving-rectangle-gray-v2",
        titleKey: "variants.pavingRectangleGrayV2Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-rectangle-gray-v2.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-rectangle-gray-v2",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-rectangle-dark-gray-v1",
        slug: "paving-rectangle-dark-gray-v1",
        titleKey: "variants.pavingRectangleDarkGrayV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-rectangle-dark-gray-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-rectangle-dark-gray-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "paving-rectangle-light-gray-v1",
        slug: "paving-rectangle-light-gray-v1",
        titleKey: "variants.pavingRectangleLightGrayV1Title",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.pavingStonesSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perSqM" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/paving-stones/paving-stone-rectangle-light-gray-v1.webp",
        fallbackImage: "/images/products/paving-stones/paving-stones.png",
        descriptionKey: "descriptions.paving-stones",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "paving-stones",
          calculatorVariantId: "paving-rectangle-light-gray-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
    ],
    specs: [{ labelKey: "thickness", valueRaw: "60 мм / 80 мм" }],
    features: [
      {
        icon: "shield",
        titleKey: "features.highWearResistance.title",
        descKey: "features.highWearResistance.desc",
      },
    ],
    applicationKeys: ["applications.pedestrianWalkways"],
  },

  curbstones: {
    id: "curbstones",
    slug: "curbstones",
    translationKey: "curbstones",
    image: "/images/products/curbstones/curbstones.png",
    galleryImages: ["/images/products/curbstones/curbstones.png"],
    badgeKey: "inStockFactory",
    calculatorProductId: "curbstones",
    defaultVariantId: "curbstone-road",
    variants: [
      {
        id: "curbstone-road",
        slug: "curbstone-road",
        sizeLabel: "100 × 30 × 15",
        subtitleKey: "variants.curbstoneRoad",
        dimensions: "1000 × 300 × 150 мм",
        price: { amount: 3500, currency: "AMD", unitKey: "perPcs" },
        weightKg: 95,
        itemsPerPallet: 18,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/curbstones/curbstones.png",
        fallbackImage: "/images/products/curbstones/curbstones.png",
        descriptionKey: "descriptions.curbstones",
        specs: [{ labelKey: "dimensions", valueRaw: "1000 × 300 × 150 мм" }],
        calculatorConfig: {
          calculatorProductId: "curbstones",
          calculatorVariantId: "curbstone-road",
          lengthMeters: 1.0,
          heightMeters: 0.3,
          thicknessCm: 15,
          itemsPerPallet: 18,
          pricePerUnit: 3500,
          weightKg: 95,
        },
      },
    ],
    specs: [
      {
        labelKey: "dimensions",
        valueRaw: "1000 × 300 × 150 мм / 1000 × 200 × 80 мм",
      },
    ],
    features: [
      {
        icon: "shield",
        titleKey: "features.roadGradeDurability.title",
        descKey: "features.roadGradeDurability.desc",
      },
    ],
    applicationKeys: ["applications.roadBordering"],
  },

  manholes: {
    id: "manholes",
    slug: "manholes",
    translationKey: "manholes",
    image: "/images/products/manholes/manhole-small-v1.webp",
    galleryImages: ["/images/products/manholes/manhole-small-v1.webp"],
    badgeKey: "inStockFactory",
    calculatorProductId: "manholes",
    defaultVariantId: "manhole-small-v1",
    variants: [
      {
        id: "manhole-small-v1",
        slug: "manhole-small-v1",
        titleKey: "variants.manholeSmallV1",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.manholeSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perPcs" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/manholes/manhole-small-v1.webp",
        fallbackImage: "/images/products/manholes/manholes.png",
        descriptionKey: "descriptions.manholes",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "manholes",
          calculatorVariantId: "manhole-small-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "manhole-large-v1",
        slug: "manhole-large-v1",
        titleKey: "variants.manholeLargeV1",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.manholeSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perPcs" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/manholes/manhole-small-v1.webp",
        fallbackImage: "/images/products/manholes/manholes.png",
        descriptionKey: "descriptions.manholes",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "manholes",
          calculatorVariantId: "manhole-large-v1",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "manhole-single-cover-v1-small",
        slug: "manhole-single-cover-v1-small",
        titleKey: "variants.manholeSingleCoverV1Small",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.manholeSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perPcs" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/manholes/manhole-single-cover-v1-small.webp",
        fallbackImage: "/images/products/manholes/manholes.png",
        descriptionKey: "descriptions.manholes",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "manholes",
          calculatorVariantId: "manhole-single-cover-v1-small",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "manhole-double-cover-v1-small",
        slug: "manhole-double-cover-v1-small",
        titleKey: "variants.manholeDoubleCoverV1Small",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.manholeSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perPcs" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/manholes/manhole-double-cover-v1-small.webp",
        fallbackImage: "/images/products/manholes/manholes.png",
        descriptionKey: "descriptions.manholes",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "manholes",
          calculatorVariantId: "manhole-double-cover-v1-small",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "manhole-cover-square-opening-v1-small",
        slug: "manhole-cover-square-opening-v1-small",
        titleKey: "variants.manholeCoverSquareOpeningV1Small",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.manholeSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perPcs" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/manholes/manhole-cover-square-opening-v1-small.webp",
        fallbackImage: "/images/products/manholes/manholes.png",
        descriptionKey: "descriptions.manholes",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "manholes",
          calculatorVariantId: "manhole-cover-square-opening-v1-small",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "manhole-cover-slot-v1-small",
        slug: "manhole-cover-slot-v1-small",
        titleKey: "variants.manholeCoverSlotV1Small",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.manholeSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perPcs" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/manholes/manhole-cover-slot-v1-small.webp",
        fallbackImage: "/images/products/manholes/manholes.png",
        descriptionKey: "descriptions.manholes",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "manholes",
          calculatorVariantId: "manhole-cover-slot-v1-small",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
      {
        id: "manhole-cover-round-hole-v1-small",
        slug: "manhole-cover-round-hole-v1-small",
        titleKey: "variants.manholeCoverRoundHoleV1Small",
        sizeLabel: "TBC",
        sizeLabelKey: "variants.sizeToBeConfirmed",
        subtitleKey: "variants.manholeSubtitle",
        dimensions: "",
        price: { amount: 0, currency: "AMD", unitKey: "perPcs" },
        priceStatus: "to_be_confirmed",
        weightKg: 0,
        itemsPerPallet: 0,
        inStock: true,
        badgeKey: "inStockFactory",
        image: "/images/products/manholes/manhole-cover-round-hole-v1-small.webp",
        fallbackImage: "/images/products/manholes/manholes.png",
        descriptionKey: "descriptions.manholes",
        specs: [],
        calculatorConfig: {
          calculatorProductId: "manholes",
          calculatorVariantId: "manhole-cover-round-hole-v1-small",
          lengthMeters: 0,
          heightMeters: 0,
          thicknessCm: 0,
          itemsPerPallet: 0,
          pricePerUnit: 0,
          weightKg: 0,
        },
      },
    ],
    specs: [{ labelKey: "diameter", valueRaw: "700 мм - 1500 мм" }],
    features: [
      {
        icon: "shield",
        titleKey: "features.heavyDutyConstruction.title",
        descKey: "features.heavyDutyConstruction.desc",
      },
    ],
    applicationKeys: ["applications.sewerageWells"],
  },
};

export function getProductDetail(slug: string): ProductDetailData | null {
  return PRODUCT_DETAILS[slug] || null;
}
